### ISSUE TITLE
Use link as input

### ISSUE THREAD

**Issue by RaitaroH** [obskyr/thehylia#10]
Ok, so why not work like, youtube-dl, bandcamp-dl, gallery-dl etc etc etc.

Not that hard either, here is a script for that:
```
#!/bin/bash
link=`echo "$1" | rev | cut -d \/ -f1 | rev` ;
python ~/bin/thehylia.py "$link" ~/Desktop/"$link"
```

That's about it. You might have it working in python, idk python. So there is bash.

**Comment by RaitaroH** [comment]
Actually I will make a pull with a few things...

**Comment by obskyr** [comment]
Thanks for the suggestion! Now that you mention it, this is a really good feature that I should've implemented a good while ago...!
