### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by Ted54** [obskyr/thehylia#3]
Hi,

Great script! It's made life a lot easier for me! :) I was wondering though, would it be possible for you to add a mass download option, to scrape the audio section? Or maybe the ability to download everything per selected letter from the alphabet (to reduce server stress somewhat)? For easy archiving purposes, that'd be pretty sweet.

A download speed indicator, if possible, would be another neat thing to have.

**Comment by obskyr** [comment]
That's outside the scope of the script, I'm afraid... I'm also thinking KHInsider might not entirely like it if stressing their servers with a full *everything* download was as easy as activating an option in a script.

However, if you'd like to download everything, writing a script for that shouldn't be too hard. What you'd do is scrape whatever index pages exist and call `thehylia.py`'s `download()` on each link. As it's a huge collection, you might want to spread it out over several machines / threads / hard drives, too - it really depends on your setup. Let me know if you'd like any help with that. It won't be part of `thehylia.py`, however.

As for the download speed indicator... I was considering it, but I realized it'd ruin piping the script's output to a file, which some people might want to do.

**Comment by RaitaroH** [comment]
@Ted54 I have made a fork of this. In my script `hylia` or the specific script `hyliabatch` I let you search for something then download everything found.
