### ISSUE TITLE
When downloading files, the script begins counting at 2 and ends one higher than the total number of items.

### ISSUE THREAD

**Issue by Vectri** [obskyr/thehylia#4]
![Image of the issue](http://i.imgur.com/mm7CCVA.png)

I am running Python 3.6.1

**Comment by obskyr** [comment]
I can't reproduce the issue on my end... It might be specific to certain soundtracks. Since it works with the soundtracks I've tried, can you tell me what soundtrack this happened with?

**Comment by Vectri** [comment]
Every soundtrack that I have tried so far has produced this result. The one in my screenshot is hyouka-op2-single-mikansei-stride. Which soundtracks do not do this for you? I imagine if I tried yours and they fail on my modified version of your script it would be a strange bug on my end, although I tested in both python 2.7 and 3.6.

**Comment by obskyr** [comment]
Ah. The reason it worked for me was that I had fixed it... but forgotten to commit and push. That's silly. Can't believe no one said anything until now...

Thanks for bringing it to my attention and fixing it! 😄☆
