### ISSUE TITLE
Errno 2 and Errno 17

### ISSUE THREAD

**Issue by ejn127** [obskyr/thehylia#9]
Hey, so i'm very new to this (spent maybe 3 or so hours trying to figure this out by looking at almost never ending tutorials) and thought I would try it out since it said it easy (I guess for people who know what they are doing). I have been getting 2 errors which are 2 and 17 by trying 2 different ways. I get similar errors with khinsider.py .

**From the terminal I get this:**

```
$ python3 thehylia.py dragon-ball-super-op01-single-chouzetsu-dynamic
/Library/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python: can't open file 'thehylia.py': [Errno 2] No such file or directory
```

**From the Python Launcher I get this:**

```
$ cd '/Users/erik/Documents/python/thehylia-master/' && '/usr/bin/pythonw' thehylia.py ps2-dragon-ball-z-3-op-ore-wa-tokoton-tomaranai '/Users/erik/Documents/python/thehylia-master/thehylia.py'  && echo Exit status: $? && exit 1
Getting song list...

An unexpected error occurred! If it isn't too much to ask, please report to https://github.com/obskyr/thehylia/issues.
Attach the following error message:

Traceback (most recent call last):
  File "thehylia.py", line 524, in <module>
    sys.exit(doIt())
  File "thehylia.py", line 493, in doIt
    success = download(soundtrack, outPath, formatOrder=formatOrder, verbose=True)
  File "thehylia.py", line 382, in download
    return Soundtrack(soundtrackId).download(path, makeDirs, formatOrder, verbose)
  File "thehylia.py", line 309, in download
    os.makedirs(os.path.abspath(os.path.realpath(path)))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/Users/erik/Documents/python/thehylia-master/thehylia.py'
```

**Since I see you ask this I'll tell you in advance:**

```
$ python3 -V
Python 3.6.5
pip3 show requests = nothing 
pip3 show beautifulsoup4 = nothing
```

I am using a MacBook Pro OS X El Capitan version 10.11.6
Thanks in advance.

**Comment by obskyr** [comment]
Sorry for getting to this so late! I've had a tumultuous and exciting life the past week.

Why the `python3` way doesn't work, I can't quite say – first, you should make sure you're in the correct directory. That means, first run `cd /Users/erik/Documents/python/thehylia-master/`, and then try `python3 thehylia.py dragon-ball-super-op01-single-chouzetsu-dynamic`. If that doesn't work, try `python3 ./thehylia.py dragon-ball-super-op01-single-chouzetsu-dynamic` (note the added `./` – that dot means "the current directory").

The reason your second try doesn't work is that you're providing `'/Users/erik/Documents/python/thehylia-master/thehylia.py'` as the *directory* argument. That means the script will try to put the songs in a directory called `thehylia.py`, which is... where the script file is. Simply remove that argument and everything should be fine.

All you should have to run is:
```bash
cd /Users/erik/Documents/python/thehylia-master/
python3 thehylia.py dragon-ball-super-op01-single-chouzetsu-dynamic
```

Or, using `pythonw`:
```bash
cd /Users/erik/Documents/python/thehylia-master/
pythonw thehylia.py ps2-dragon-ball-z-3-op-ore-wa-tokoton-tomaranai
```

Lemme know whether it works out!

**Comment by ejn127** [comment]
It's no problem, I'm glad things are going well for you! 

I think the problem I was having was that I was trying to run the _thehylia.py_ through the python (or python3) directory. I made sure to use _cd /Users/erik/Documents/python/thehylia-master/_ first and the python3 way worked, I also used the same method for khinsider and it worked too. Besides your python launcher tip (because for some reason I just don't get how to use the pyhton launcher) all of your suggestions worked! Thank you so much!

**Comment by obskyr** [comment]
Glad I could help! I see how it could be confusing if you haven't used the terminal a lot before – people who are used to it know the quirks of it, but newcomers do have to learn a bunch of odd systems.

Basically, the main thing here was: when using the terminal, you're always *in* a directory (the "current working directory"). File paths provided can be absolute (those that start with `/`) or relative, and are then often relative to where you currently are. For example, if you're in `/Users/erik/Documents/python/`, running `thehylia.py` will actually run `/Users/erik/Documents/python/thehylia.py`. If you're not there, you can't run it just by typing `thehylia.py`, since that'd point to a filename in some other directory. In that case, you have to `cd` (**c**hange **d**irectory) to where the file is to run it.

Thanks a bundle for using thehylia.py! Enjoy! 😄
